### PR TITLE
Add support for the Bayer Contour USB glucose meter.

### PR DESCRIPTION
**Pull request by flupzor**
This implements the CLSI LIS1a and LIS2a2 protocols as mixins, which can be used with HIDDevice or SerialDevice to create a device capable of communicating using one of these protocols.

The Bayer Contour USB driver utilizes the LIS1a and LIS2a2 mixins together with a custom TLV-type protocol (probably created by Bayer) to retrieve the glucose results over USB Hid messages. Serial communication has not been implemented yet.

Note that I tried creating a driver for the Bayer Contour TS as well, which uses a 3.5mm TRS cable for serial communication using TTL-logic level with baudrate of 9600. For some reason the only data I can get back was something like 0x06, or 0x05 (I can't remember what it was exactly) when I wrote either 0x05 or 0x06. Note that I didn't use the official cable, since it is impossible to get one in the Netherlands (Altough I doubt that's the problem).

### CODE REVIEW

**Comment by flupzor** [comment]
The test ``test_build_custom_epoch_negative_failure`` fails on master as well, if I run it locally.

**Comment by Flameeyes** [comment]
Sorry for the delay! I'm currently on a work trip so I won't probably have enough time to review this until I go back home. On the bright side I do have an original cable at home so I can give a try of that.

One thing that I would like to ask if you don't mind is to take a look if it makes sense to write the description on the protocol on https://github.com/Flameeyes/glucometer-protocols instead of the code, and maybe convert the code to use [construct](https://construct.readthedocs.io/en/latest/) as I used for the other drivers recently.

Also at least for UK/Ireland it seems like Bayer is dropping their name everywhere, and the brand used is Ascensia instead. I would just call the driver `contourusb`.

**Comment by flupzor** [comment]
No problem. I'm curious if the original cable would work. Even with the original software I couldn't get it to work.

I've based the protocol on the CLSI LIS1-a and LIS2-A2 standards, sadly they're not free standards. I'm not entirely sure what makes sense here. I can describe the protocol, but I would be re-writing the standard. At least the Bayer-specific parts I can describe.

I'll look at using construct. I wrote most of the code an half year ago, and recently finished it. I think at time construct wasn't used yet.

I also noticed that they use 'Ascensia', at my pharmacy, I assumed it was the other way around, that Bayer bought Ascensia and that they'll be using the Bayer brand in the future, but this makes sense. I'll rename it.

**Comment by Flameeyes** [comment]
So looks like Ascensia actually published their specs (see issue #61), so this might be possible to be implemented referencing those (and thus not need a full reference to LIS).

**Comment by Flameeyes** [comment]
48e89e53d9983312e36ae6c353da9b94fa46b590 should take care of this one too. Thank you for your patience, and sorry for missing the point about LIS :( Now I have a copy of the standards so I can understand what you mean.

**Comment by flupzor** [comment]
No worries :) I didn't really have time to continue working on this, and kind of forgot about it.

**Comment by arvchristos** [comment]
Thank you @flupzor for the ideas ! Happy to know I didn't intervene in your implementation.

**Pull request closed without merging**
