### PR TITLE
Python 2.7 support

### PR DESCRIPTION
**Pull request by DorianScholz**
As my Ubuntu 14.04 still has Python 2.7 as default, I made a few minor changes to make it run on Python 2.7 as well.
I tested it also on Python 3, so this does not seem to break anything there...

### CODE REVIEW

**Comment by Flameeyes** [comment]
So part of the reason why I wrote this with Python 3 in mind, and not cared about Python 2.7 is that the binary data handling changed significantly, and I maintain this under Python 3.

I'm not sure if adding partial support for Python 2.7 is a good idea, because I won't really have the time to test it, so it may break later on simply because I'm not paying attention. Effectively. 2.7 and 3 are significantly different languages, and I started from the beginning supporting Python 3 only...

**Comment by DorianScholz** [comment]
Sure, thats understandable.
Then I would propose to add some checks at startup, that it is actually running on Python 3 and otherwise exit with an explanation.
Currently, when run with Python 2.7, it just fails at weired places, that do not really give a hint what went wrong...

Further, maybe explicitly writing "python3" instead of just "python" in the shebang would help, since "python" still refers to Python 2.7 on many systems, even though Python 3 is installed as well.

**Comment by Flameeyes** [comment]
Sorry for not updating this in a while; do you know if python3 is universally present as a name? I have no problem with changing that if it is.

**Comment by DorianScholz** [comment]
According to https://www.python.org/dev/peps/pep-0394/ using "python3" is recommended for Python scripts not compatible with Python 2.
So this would be the right way to go I think.

**Comment by Flameeyes** [comment]
Thank you! I have changed the shebang now and it should be looking for python3 explicitly.

**Pull request closed without merging**
